# Etapa 1: builder
FROM python:3.11-alpine AS builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 2: final
FROM python:3.11-alpine

WORKDIR /app

# Copiar dependencias
COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY app.py .

# Crear usuario y carpeta con permisos
RUN adduser -D appuser && mkdir downloads && chown -R appuser /app

# Cambiar a usuario seguro
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]