FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Crear carpeta con permisos
RUN mkdir downloads && adduser -D appuser && chown -R appuser /app

# Cambiar a usuario seguro
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]