# Etapa 1: builder
FROM python:3.11-alpine AS builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 2: final
FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY app.py .

RUN adduser -D appuser
USER appuser

RUN mkdir downloads

EXPOSE 5000

CMD ["python", "app.py"]
